### ISSUE TITLE
Users have access to others home directory including mail.

### ISSUE THREAD

**Issue by gmcclins** [hashbang/shell-etc#11]
I seen *lrvick* asking this morning if irc user *woompydoompydoo* filed a report on this. Since no report was made yet, I decided to go ahead and submit this. I actually brought this up before in irc, but I guess I should have filed the report.

*woompydoompydoo* is correct. Users do have access to other users home directories, including Mail. I haven't went further than /home/xxx/Mail for privacy, but looking at cur, new, tmp permissions I am pretty sure that I could just read other users emails in nano.

*4 drwxr-xr-x.  2 xxxx 3000 4096 May 19 05:04 cur*
*4 drwxr-xr-x.  2 xxxx 3000 4096 May 19 05:04 new*
*4 drwxr-xr-x.  2 xxxx 3000 4096 May 11 18:14 tmp*

This is caused by most users sharing the *group 3000. It seems legacy users and admins are not affected by this. For a list of affected users see  `getent passwd`. Anyone who shares the same group has access to eachothers files. daurnimator also stated last night in irc that you can also see there is a problem by checking `getenv group`

I see that there are already a few test accounts created and that they also share the same group 3000, so this all can easily be tested using one of those accounts or by creating a new account and then checking file permissions.

*28 -rw-------. 1 xxxxx 3000 27271 Jun  9 22:00 .bash_history*
*4 -rw-r--r--.   1 xxxxx 3000   220 May 11 16:42 .bash_logout*
*4 -rw-r--r--.   1 xxxxxx 3000  2129 Jun  3 16:16 .bash_profile*

**Comment by KellerFuchs** [comment]
@gmcclins This will be fixed when hashbang/provisor#25 is (completely) resolved.
Thanks again for reporting the issue.

**Comment by KellerFuchs** [comment]
Fixed.
