### ISSUE TITLE
Unable to remove certain files

### ISSUE THREAD

**Issue by KellerFuchs** [hashbang/shell-etc#123]
Some files cannot be unlinked on the servers, leading to automation failure:
- `/etc/{passwd,group}` on
  - [x] `da1`,
  - [x] `sf1` and
  - [ ] `to1`.
- [x] `/usr/bin/ruby2.1` on `ny1`.

This prevents the correct deployment of package and `shell-etc` updates.

`lsof` reports no user of those files.  This might be a filesystem issue.

**Comment by KellerFuchs** [comment]
@hashbang/administrators As mentioned, this breaks our ability to deploy `shell-etc` updates, so we should fix it ASAP

**Comment by ChickenNuggers** [comment]
I've found a few things that are not the issue:

 * `a` or `i` file attribute
 * SELinux context for file

**Comment by KellerFuchs** [comment]
Confirmed filesystem issue on `ny1`, fixed from initramfs.

Scheduled reboot of other 3 servers between 23.00 and 00.00 UTC.

**Comment by KellerFuchs** [comment]
OK, for whatever reason, `to1` came back clean, as far as fsck is concerned, yet it still exhibits the issue:
> root@to1:~# etckeeper vcs reset --hard 79e151f87cdd618822ae23df755d9df677d28716^
warning: unable to unlink group+: Device or resource busy
error: unable to unlink old 'group' (Device or resource busy)
error: unable to unlink old 'passwd' (Device or resource busy)
fatal: Could not reset index file to revision '79e151f87cdd618822ae23df755d9df677d28716^'.

@hashbang/administrators Thoughts?

**Comment by ChickenNuggers** [comment]
Burn it with fire?

Did you make sure to check all the attributes on the file? Make sure there's no weird SELinux policy, no `a` or `i` in `lsattr`?

**Comment by ChickenNuggers** [comment]
Bump: `php5-cli` on at least ny1 is now broken.
