### ISSUE TITLE
Install `php`

### ISSUE THREAD

**Issue by dgadelha** [hashbang/shell-etc#125]
Would be awesome to have PHP (preferentially the newest, version 7) installed in the servers.

**Comment by KellerFuchs** [comment]
Given that there is no backport for PHP 7, I would strongly advise for PHP 6 instead.

@dgadelha Please clarify:
- What is needed?  PHP-FPM?  Just the PHP CLI?
- Are any additional packages/libraries required?
- May I ask what you need it for?

**Comment by dgadelha** [comment]
PHP 6 is great too.

Well, for lighttpd I just need the PHP CGI, but PHP CLI helps doing other stuff too.

About PHP extensions (generally they're distributed as another package), most common to see are: bz2, curl, dev, gd, imagick, imap, intl, json, mbstring, mcrypt, mysql, PDO (mysql, sqlite), sqlite3, ssh2, xml, zip.

**Comment by KellerFuchs** [comment]
Could you clarify what you actually need? (In terms of installed extensions)

**Comment by dgadelha** [comment]
Only curl, PDO and zip are okay :)

**Comment by KellerFuchs** [comment]
OK, so that would be the PHP CLI, CGI and FPM, and the curl, PDO and zip extensions.

Unfortunately, I just found out that PHP 6 isn't in jessie either, and there are no PHP backports, so we can either:
- Install from `testing`: I would rather avoid it, as we might get in dependency hell pretty quick.
- Request a backport or build it ourselves.
- Install PHP 5.

**Comment by dgadelha** [comment]
5 is okay :)

**Comment by KellerFuchs** [comment]
OK.

Then, I would pull in `php5-cli`, `php5-cgi`, `php5-curl`, `php5-fpm`.
They pull the following as dependencies: `libonig2` (regexp lib), `libqdbm14`, `php5-common` and `php5-json`.

Regarding PDO, which DB driver do you need?

**Comment by dgadelha** [comment]
mysql and sqlite only :)

**Comment by KellerFuchs** [comment]
OK, `php5-mysql` and `php5-sqlite` only add `libmysqlclient18` and `mysql-common` as dependencies.

**Comment by dgadelha** [comment]
Alright

**Comment by KellerFuchs** [comment]
Erg, of course I ran into #123 again...

@dgadelha: Given that we can't currently deploy changes, this will have to wait a bit  :V

**Comment by dgadelha** [comment]
:/ okay then

**Comment by KellerFuchs** [comment]
@dgadelha Sorry it took shamefully long, but #123 should be resolved tonight, so I can run an install/deploy afterwards.

**Comment by dgadelha** [comment]
That's not a problem, thanks!
