### ISSUE TITLE
Automatically clone dotfiles for users with -all- shells

### ISSUE THREAD

**Issue by RyanSquared** [hashbang/shell-etc#150]
Two methods to do this is to either add in a user RC file into `/etc/skel`, or add in something to `/etc/profile.d` to do so. The way this would be possible is, on the first run of the file in `/etc/profile.d`, create a file in the user's `$HOME` called something like `.is-dotfiles-installed`. If the file already exists, exit. Otherwise, do the same thing in the current `.bash_profile`.

**Comment by RyanSquared** [comment]
Another thought: If any files at all are found in $HOME, just don't run it, but prompt the user before running it?

**Comment by KellerFuchs** [comment]
On Mon, Feb 20, 2017 at 04:03:57PM -0800, Ryan wrote:
> Two methods to do this is to either add in a user RC file into `/etc/skel`
> or add in something to `/etc/profile.d` to do so.

I would be in favor of the profile.d solution, given that it minimizes the
amount of shell-specific parts, and it should work, given that the
/etc/profile.d emulation for ZSH is in /etc.

However, we don't need to create extra dotfiles clutter to check if .dotfiles
was cloned.  Basically moving the current bash_profile script to profile.d,
removing bashisms and adding something like that should work:

> if [ -d "${HOME}/.dotfiles" ]; then
>   return
> fi

(Note that I didn't test this, I said /should/ work...)

**Comment by KellerFuchs** [comment]
On Mon, Feb 20, 2017 at 04:15:47PM -0800, Ryan wrote:
> Another thought: If any files at all are found in $HOME, just don't run it, but prompt the user before running it?

profile.d is run for non-interactive shells too, so we should NOT prompt.
