### ISSUE TITLE
Request: mksh

### ISSUE THREAD

**Issue by rqcy** [hashbang/shell-etc#157]
Hi, would it be possible to install mksh shell at hashbang? Thanks!

**Comment by KellerFuchs** [comment]
Hi!

We are currently fixing over a few things when it comes to our ability to deploy changes (actually, running mockups of the servers in which we can run an install, and get the corresponding `shell-etc` commits).
Once this is fixed, I will happily install `mksh`; the version available in Debian Jessie is v50d-5, is that fine?

**Comment by rqcy** [comment]
> We are currently fixing over a few things when it comes to our ability
> to deploy changes (actually, running mockups of the servers in which
> we can run an install, and get the corresponding `shell-etc` commits).
>
> Once this is fixed, I will happily install `mksh`; the version
> available in Debian Jessie is v50d-5, is that fine?

Thanks for reply.  This version looks quite old, but I think it's OK.

Thanks again! ☺

**Comment by KellerFuchs** [comment]
If you want, you can send a PR to use the version from `jessie-backports` (54-2~bpo8+1).

**Comment by rqcy** [comment]
> If you want, you can send a PR to use the version from `jessie-backports` (54-2~bpo8+1).

Could you point me out to the place in the repo where this is
configured/declared?

**Comment by KellerFuchs** [comment]
Sure!

On Debian systems, this is configured in [`/etc/apt/preferences.d`](https://github.com/hashbang/shell-etc/tree/master/apt/preferences.d).
Feel free to copy what the file for `mosh` does, for instance.

**Comment by KellerFuchs** [comment]
@rqcy Sorry this took forever, but `mksh` is now installed from backports.
