### ISSUE TITLE
Use etc/conf from apt/dpkg?

### ISSUE THREAD

**Issue by mayli** [hashbang/shell-etc#164]
It seems the current shell-etc contains tons of non-hashbang configs, most of them are from upstream Debian packages. I think we can remove them add those files to .gitignore and let dpkg manage them.

And also, we should cleanup obsolete config files such as `.java`, `lighttpd`, `apache2/conf-available`.

**Comment by lrvick** [comment]
I second this. 

@KellerFuchs @daurnimator thoughts?

implementation wise we would  just .gitignore * and only add hashbang specific changes.

Then this is just an overlay repo and much easier for people to follow.

**Comment by daurnimator** [comment]
I'm okay with this.

**Comment by lrvick** [comment]
@mayli Do you already have suggested commands to identify hashbang specific changes and mask everything else?

**Comment by KellerFuchs** [comment]
Let's move the discussion to the pull request.

I have no issue with conffiles for obsolete packages being dropped, obviously.
However, I don't think not-versionning default conffiles is a good idea; I described the main reasons in the PR.
