### ISSUE TITLE
request: minetest-server and/or SQlite 3

### ISSUE THREAD

**Issue by the1glorfindel** [hashbang/shell-etc#174]
Hi, I was wondering if you could install minetest-server or else SQlite 3 so that I could compile it myself.
Thanks, -Glorfindel

**Comment by mayli** [comment]
You could compile everything in your user dir without any issue. Or you can download the precompiled bits from gitlab and unpack at homedir.

**Comment by the1glorfindel** [comment]
Thanks for the suggestions! 
I've looked up the directions for compiling SQlite and I'm pretty sure I would have issues, lol.
I'll have to look up the gitlab precompiled thing you mentioned, sounds promising, thanks!

**Comment by KellerFuchs** [comment]
@the1glorfindel I have no issue installing the SQLite header files, and/or `minetest-server` from `jessie-backports`; the people maintaining the minetest [seem pretty reactive](https://tracker.debian.org/pkg/minetest) package seem pretty reactuve, both for uploads to `sid` and `jessie-backports`.

As always, be considerate of other users and don't use disproportionate amount of ressources.

**Comment by the1glorfindel** [comment]
@KellerFuchs thanks a bunch!
I am curious though, what would be considered a disproportionate amount of resources?

**Comment by RyanSquared** [comment]
Anything that would disturb the activities of other users, usually is a good guide. I mentally red flag myself when I go over 20% of any resource on my desktop, as a note.

**Comment by the1glorfindel** [comment]
@RyanSquared ahh, ok. Thanks :)

**Comment by farooqkz** [comment]
I don't think it's a good idea to run a Minetest server on hashbang.

**Comment by the1glorfindel** [comment]
It's been a year and last I checked it hasn't been installed.
I'm hosting on a vps now
