### ISSUE TITLE
request: jungle colorscheme for ranger

### ISSUE THREAD

**Issue by benalb** [hashbang/shell-etc#177]
I would like to get the jungle colorscheme in ranger. 
I tried to copy the jungle.py file to ~/config/ranger/colorschemes/jungle.py, but ranger seems not to find it:

```
benalb@to1:~$ ranger 
Cannot locate colorscheme `jungle '
benalb@to1:~$ cat .config/ranger/rc.conf 
set colorscheme jungle 
map dd delete
map DD cut
benalb@to1:~$ ls .config/ranger/ -l
total 16
-rw------- 1 benalb benalb   15 Jul 22 21:28 bookmarks
drwx------ 2 benalb benalb 4096 Jul 22 21:23 colorschemes
-rw------- 1 benalb benalb   48 Jul 22 21:28 history
-rw------- 1 benalb benalb   49 Jul 22 21:23 rc.conf
-rw------- 1 benalb benalb    0 Jul 22 21:09 tagged
```

Thanks.

**Comment by KellerFuchs** [comment]
Hi, @benalb 

As far as I can see, there is no Debian packages for ranger colorschemes.
Indeed, the `ranger` package already contains `/usr/share/pyshared/ranger/colorschemes/jungle.py`.

Moreover, I do not get any error when putting `set colorscheme jungle` in `~/.config/ranger/rc.conf`:
```
 kellerfuchs@to1  ~  ranger
 kellerfuchs@to1  ~  cat ~/.config/ranger/rc.conf
set colorscheme jungle
```

**Comment by benalb** [comment]
removed the .config/ranger directory, launched ranger, :set colorscheme jungle, it works 
recreated the rc.conf with the set colorscheme jungle, it works.

So it seems it was my fault, maybe strange character on copy and paste. IDK. 
I am very sorry for any inconvenience. Closing the issue.

**Comment by KellerFuchs** [comment]
No problem, and thanks for reporting this is solved.
