### ISSUE TITLE
Unuseable keys in cron.daily/gpg-keyring

### ISSUE THREAD

**Issue by KellerFuchs** [hashbang/shell-etc#189]
- [x] [@drGrove](https://github.com/hashbang/shell-etc/pull/190) Key revoked on 2017-10-08
- [x] [@KellerFuchs](https://github.com/hashbang/shell-etc/pull/188) Subkeys expired 2017-10-22
- [ ] @RyanSquared Key expired on 2017-10-29

**Comment by drGrove** [comment]
Resolve drGrove with #190

**Comment by KellerFuchs** [comment]
Last item closed by #191
