### ISSUE TITLE
requesting package libjpeg 

### ISSUE THREAD

**Issue by Liumkattan** [hashbang/shell-etc#192]

**Comment by KellerFuchs** [comment]
@Liumkattan There is no Debian package called `libjpeg`, and `libjpeg62-turbo` is already installed.
Do you need the development headers for it, rather?  (`libjpeg62-turbo-dev`)

**Comment by Liumkattan** [comment]
i meant libjpeg-dev but it is solved now python cherrypy pack required that lib but i found a way around so if there is no one else need the lib it's not required

**Comment by KellerFuchs** [comment]
OK, I'm glad to hear that.
