### ISSUE TITLE
~/Public/index.html describes a userdir setup for httpd, but can't find it.

### ISSUE THREAD

**Issue by daveloyall** [hashbang/shell-etc#24]
I tried sebboh.hashbang.sh and hashbang.sh/~sebboh/ but could not locate my ~/Public directory.

Note: I'm not saying this is needed, just saying that if it's not available maybe ~/Public/index.html should be altered.

Meanwhile, is this the correct place to provide feedback like this?

**Comment by ChickenNuggers** [comment]
It should actually be in the dotfiles repository. Is there not a ~/Public in the dotfiles? I'm also not sure if ~/Public is accessible via web yet.

Or do I misunderstand your question?

**Comment by KellerFuchs** [comment]
I think @daveloyall meant that their `~/Public` directory cannot be reached on the standard HTTP port.

@daveloyall This is normal: the default dotfiles contain a `systemd` unit-file that lets you run the Python `SimpleHTTPServer` to serve that directory, but not on port 80 (or 443).
Multiplexing user's HTTPds is something @Aagat is working on, IIRC.
