### ISSUE TITLE
permissions between `shell-etc` and actual `/etc` on `ny1` are out of sync.

### ISSUE THREAD

**Issue by daveloyall** [hashbang/shell-etc#26]
Here is what permissions look like in `/etc/apt` according to `shell-etc`.

    sebboh@ny1:~$ ls -alR ~/src/shell-etc/apt/
    /home/sebboh/src/shell-etc/apt/:
    total 24
    drwxr-x---.   4 sebboh 3000 4096 Sep 21 17:41 .
    drwxr-x---. 108 sebboh 3000 4096 Sep 21 17:41 ..
    drwxr-x---.   2 sebboh 3000 4096 Sep 21 17:41 apt.conf.d
    -rw-r-----.   1 sebboh 3000  156 Sep 21 17:41 preferences
    -rw-r-----.   1 sebboh 3000  343 Sep 21 17:41 sources.list
    drwxr-x---.   2 sebboh 3000 4096 Sep 21 17:41 trusted.gpg.d
    
    /home/sebboh/src/shell-etc/apt/apt.conf.d:
    total 44
    drwxr-x---. 2 sebboh 3000 4096 Sep 21 17:41 .
    drwxr-x---. 4 sebboh 3000 4096 Sep 21 17:41 ..
    -rw-r-----. 1 sebboh 3000   82 Sep 21 17:41 00CDMountPoint
    -rw-r-----. 1 sebboh 3000   40 Sep 21 17:41 00trustcdrom
    -rw-r-----. 1 sebboh 3000  643 Sep 21 17:41 01autoremove
    -rw-r-----. 1 sebboh 3000  548 Sep 21 17:41 01autoremove-kernels
    -rw-r-----. 1 sebboh 3000  369 Sep 21 17:41 05etckeeper
    -rw-r-----. 1 sebboh 3000 3945 Sep 21 17:41 50unattended-upgrades
    -rw-r-----. 1 sebboh 3000  182 Sep 21 17:41 70debconf
    -rw-r-----. 1 sebboh 3000   80 Sep 21 17:41 90cloud-init-pipelining
    -rw-r-----. 1 sebboh 3000   31 Sep 21 17:41 99defaultrelease
    
    /home/sebboh/src/shell-etc/apt/trusted.gpg.d:
    total 44
    drwxr-x---. 2 sebboh 3000 4096 Sep 21 17:41 .
    drwxr-x---. 4 sebboh 3000 4096 Sep 21 17:41 ..
    -rw-r-----. 1 sebboh 3000 5138 Sep 21 17:41 debian-archive-jessie-automatic.gpg
    -rw-r-----. 1 sebboh 3000 5147 Sep 21 17:41 debian-archive-jessie-security-automatic.gpg
    -rw-r-----. 1 sebboh 3000 2775 Sep 21 17:41 debian-archive-jessie-stable.gpg
    -rw-r-----. 1 sebboh 3000 4084 Sep 21 17:41 debian-archive-squeeze-automatic.gpg
    -rw-r-----. 1 sebboh 3000 2853 Sep 21 17:41 debian-archive-squeeze-stable.gpg
    -rw-r-----. 1 sebboh 3000 3780 Sep 21 17:41 debian-archive-wheezy-automatic.gpg
    -rw-r-----. 1 sebboh 3000 2851 Sep 21 17:41 debian-archive-wheezy-stable.gpg
    sebboh@ny1:~$ 

But, this is what they look like on the machine ny1:

    sebboh@ny1:~$ ls -alR /etc/apt/
    /etc/apt/:
    total 40
    drwxr-xr-x.   6 root root  4096 Jul  3 05:54 .
    drwxr-x--x. 114 root root 12288 Sep 17 00:54 ..
    drwxr-xr-x.   2 root root  4096 Sep  6 13:19 apt.conf.d
    -rw-r-----.   1 root root   156 May 24 12:15 preferences
    drwxr-xr-x.   2 root root  4096 Apr 13 16:52 preferences.d
    -rw-r--r--.   1 root root   343 Jul  3 05:54 sources.list
    -rw-r--r--.   1 root root     0 May  2 03:14 sources.list~
    drwxr-xr-x.   2 root root  4096 Apr 13 16:52 sources.list.d
    drwxr-xr-x.   2 root root  4096 May 11 19:35 trusted.gpg.d
    
    /etc/apt/apt.conf.d:
    total 44
    drwxr-xr-x. 2 root root 4096 Sep  6 13:19 .
    drwxr-xr-x. 6 root root 4096 Jul  3 05:54 ..
    -rw-r--r--. 1 root root   82 May 11 19:35 00CDMountPoint
    -rw-r--r--. 1 root root   40 May 11 19:35 00trustcdrom
    -rw-r--r--. 1 root root  643 May 11 19:35 01autoremove
    -rw-r--r--. 1 root root  548 Aug 17 05:45 01autoremove-kernels
    -rw-r--r--. 1 root root  369 May 11 19:35 05etckeeper
    -rw-r-----. 1 root root 3945 Jul  3 05:36 50unattended-upgrades
    -rw-r--r--. 1 root root  182 May 11 19:35 70debconf
    -rw-r--r--. 1 root root   80 May 11 19:43 90cloud-init-pipelining
    -rw-r--r--. 1 root root   31 May 11 19:35 99defaultrelease
    
    /etc/apt/preferences.d:
    total 8
    drwxr-xr-x. 2 root root 4096 Apr 13 16:52 .
    drwxr-xr-x. 6 root root 4096 Jul  3 05:54 ..
    
    /etc/apt/sources.list.d:
    total 8
    drwxr-xr-x. 2 root root 4096 Apr 13 16:52 .
    drwxr-xr-x. 6 root root 4096 Jul  3 05:54 ..
    
    /etc/apt/trusted.gpg.d:
    total 44
    drwxr-xr-x. 2 root root 4096 May 11 19:35 .
    drwxr-xr-x. 6 root root 4096 Jul  3 05:54 ..
    -rw-r--r--. 1 root root 5138 May 11 19:35 debian-archive-jessie-automatic.gpg
    -rw-r--r--. 1 root root 5147 May 11 19:35 debian-archive-jessie-security-automatic.gpg
    -rw-r--r--. 1 root root 2775 May 11 19:35 debian-archive-jessie-stable.gpg
    -rw-r--r--. 1 root root 4084 May 11 19:35 debian-archive-squeeze-automatic.gpg
    -rw-r--r--. 1 root root 2853 May 11 19:35 debian-archive-squeeze-stable.gpg
    -rw-r--r--. 1 root root 3780 May 11 19:35 debian-archive-wheezy-automatic.gpg
    -rw-r--r--. 1 root root 2851 May 11 19:35 debian-archive-wheezy-stable.gpg

Seems to me that the machine is "less wrong" than the repo.

**Comment by daveloyall** [comment]
Hm, according to http://etckeeper.branchable.com/README/:

> [...] file metadata is stored separately. Among other chores, etckeeper init sets up a pre-commit hook that stores metadata about file owners and permissions into a /etc/.etckeeper file. This metadata is stored in version control along with everything else, and can be applied if the repo should need to be checked back out. [...]

So, it should only be necessary to confirm that etckeeper has the same stored permissions for each file as those which are on the disk?

**Comment by daveloyall** [comment]
I believe that `etckeeper` is out of sync with the machine `ny1`.

Here's what the config file `.etckeeper` says (abbreviated):

    maybe chmod 0755 'apt'
    maybe chmod 0755 'apt/apt.conf.d'
    maybe chmod 0644 'apt/apt.conf.d/00CDMountPoint'
    maybe chmod 0644 'apt/apt.conf.d/00trustcdrom'
    maybe chmod 0644 'apt/apt.conf.d/01autoremove'
    maybe chmod 0644 'apt/apt.conf.d/01autoremove-kernels'
    maybe chmod 0644 'apt/apt.conf.d/05etckeeper'
    maybe chmod 0644 'apt/apt.conf.d/50unattended-upgrades'
    maybe chmod 0644 'apt/apt.conf.d/70debconf'
    maybe chmod 0644 'apt/apt.conf.d/90cloud-init-pipelining'
    maybe chmod 0644 'apt/apt.conf.d/99defaultrelease'
    maybe chmod 0644 'apt/preferences'
    maybe chmod 0755 'apt/preferences.d'
    maybe chmod 0644 'apt/sources.list'
    maybe chmod 0755 'apt/sources.list.d'
    maybe chmod 0755 'apt/trusted.gpg.d'
    maybe chmod 0644 'apt/trusted.gpg.d/debian-archive-jessie-automatic.gpg'
    maybe chmod 0644 'apt/trusted.gpg.d/debian-archive-jessie-security-automatic.gpg'
    maybe chmod 0644 'apt/trusted.gpg.d/debian-archive-jessie-stable.gpg'
    maybe chmod 0644 'apt/trusted.gpg.d/debian-archive-squeeze-automatic.gpg'
    maybe chmod 0644 'apt/trusted.gpg.d/debian-archive-squeeze-stable.gpg'
    maybe chmod 0644 'apt/trusted.gpg.d/debian-archive-wheezy-automatic.gpg'
    maybe chmod 0644 'apt/trusted.gpg.d/debian-archive-wheezy-stable.gpg'
    
For your reference:

    -rw-r--r-- = 0644
    -rwxr-xr-x = 0755
    -rw-r----- = 0640

I believe that `etckeeper` is "less wrong" than the machine.

If there is some operation you can perform to make all the files in `/etc` get their permissions updated by `etckeeper`, I say go for it, perhaps after a dry-run.

If there is no such feature, then I can help you author a script that will verify that the on-disk permissions for each file in `etc` match what is in the `.etckeeper` file, or emit the pathname for files that don't match.

Cheers,
--sebboh

**Comment by KellerFuchs** [comment]
Fixed.
