### ISSUE TITLE
apt-cache search emacs24 fails due to lacking read permissions in /etc/apt/...

### ISSUE THREAD

**Issue by daveloyall** [hashbang/shell-etc#27]
Hello!

    sebboh@ny1:~$ apt-cache search emacs24
    E: Opening configuration file /etc/apt/apt.conf.d/50unattended-upgrades - ifstream::ifstream (13: Permission denied)

If you look at the directory `/etc/apt/apt.conf.d`, you'll see this:

    /etc/apt/apt.conf.d:
    total 44
    drwxr-xr-x. 2 root root 4096 Sep  6 13:19 .
    drwxr-xr-x. 6 root root 4096 Jul  3 05:54 ..
    -rw-r--r--. 1 root root   82 May 11 19:35 00CDMountPoint
    -rw-r--r--. 1 root root   40 May 11 19:35 00trustcdrom
    -rw-r--r--. 1 root root  643 May 11 19:35 01autoremove
    -rw-r--r--. 1 root root  548 Aug 17 05:45 01autoremove-kernels
    -rw-r--r--. 1 root root  369 May 11 19:35 05etckeeper
    -rw-r-----. 1 root root 3945 Jul  3 05:36 50unattended-upgrades
    -rw-r--r--. 1 root root  182 May 11 19:35 70debconf
    -rw-r--r--. 1 root root   80 May 11 19:43 90cloud-init-pipelining
    -rw-r--r--. 1 root root   31 May 11 19:35 99defaultrelease

As you can see, the `50unattended-upgrades` file has different permissions than the rest.  This is on the machine `ny1`!

If you actually look in `shell-etc`, you'll see that the permissions for that file match between machine and repo.. but the permissions for the rest of the files do not!  I'll file a separate bug about that: #26.

**Comment by KellerFuchs** [comment]
This was due to a systematic permission issue when deploying etckeeper changes (and later commiting wrong permissions in etckeeper).

I believe this is now fixed.
