### ISSUE TITLE
Migrate user pruning to a systemd service or cron job.

### ISSUE THREAD

**Issue by lrvick** [hashbang/shell-etc#5]
old prune script: https://github.com/hashbang/shell-server/blob/master/root/scripts/prune.sh

Should also update to auto-prune any accounts that begin with 'test' and are over 24 hours old.

**Comment by AlissaSquared** [comment]
I'll get to working on a script that will automatically delete all users with a home directory of /home starting with "test" tomorrow after school, sometime before or after I look at hashbangctl.

**Comment by AlissaSquared** [comment]
I'm still working on this, but I don't exactly have time. Would like to see if anyone else would like to propose a system.

**Comment by KellerFuchs** [comment]
This was done by https://github.com/hashbang/shell-etc/pull/30
