### ISSUE TITLE
Undelivered Mail Returned to Sender for root

### ISSUE THREAD

**Issue by geoffmcc** [hashbang/shell-etc#63]
I was taking a look at hashbangctl and it caused a security alert to be sent to root, but the mail went undelivered and was returned back to me. I then tried to just send a test email to root and that too was also returned with same error.

> **error: <root@hashbang.sh>: mail for hashbang.sh loops back to myself**

I think the issue is with _/postfix/main.cf_

`mydestination = $myhostname` 

I think it actually needs to be 

`mydestination = $mydomain`

I was going to submit a PR on this after making the change, but since I am not 100% sure I figured it best to file as an issue. If this is the case, unless someone fixes it first I can always submit the PR once I get word as I already made the adjustment on my clone of repo. But really with it being such a quick thing, I'm sure anyone can get to it at anytime. 

If something more is going on here at least it will open up discussion and maybe I will learn something new.

**Comment by KellerFuchs** [comment]
No, the issue is not with `mydestination`.
Basically, there are two problems:
1. there is an issue with `sudo(8)` that makes it send mail to `root` whenever someone uses it (it seems to be a PAM snafu, not sure what yet).
2. there is no `root@hashbang.sh` mailbox, so that mail bounces.

Regarding (2), I plan to deploy mailing lists at some point, but didn't have time yet.

**Comment by KellerFuchs** [comment]
Part (1) fixed by #64.

**Comment by geoffmcc** [comment]
I was already looking into the list option myself trying to see if /etc/aliases would accept a group rather than usernames (obviously not preferred), but i don't think that is the right approach. I will still look into it and if get before you, at least I cleared one of the many things off your plate

**Comment by KellerFuchs** [comment]
@geoffmcc AFAIK, `/etc/aliases` doesn't take Unix groups.
Also, the mail routing is done on `mail.hashbang.sh`, which doesn't use LDAP as its user DB.

**Comment by KellerFuchs** [comment]
PS: @geoffmcc Don't take it to mean you shouldn't propose a solution and implement it, just that the action for that is going to be in [`docker-postfix`](https://github.com/hashbang/docker-postfix), or in a new repo if you pick a new piece of software for the “mailing lists” (or whatever we call those).

The solution I had in mind was running [Schleuder](http://schleuder2.nadir.org/) - an encrypted mailing-list system - and forward mail to the mailing lists from the postfix container.  Unfortunately, I `ENOTIME`d pretty hard lately, and also it looks like Schleuder cannot natively speak LMTP nor could I find a simple/stupid LMTP daemon, so it might involve running a second instance of Postfix to get mail handed over to the container (or find/write a small LMTP implementation).

**Comment by daurnimator** [comment]
> Part (1) fixed by #64.

I'm not sure how using NOEXEC in sudoers turned off sending mail?

Shouldn't we be modifying one of the `mail_*` vars?

**Comment by KellerFuchs** [comment]
@daurnimator Removing the attempt to get `sudoers` data from NSS solved it.
It's just that I did some cleanup in the sudo config while I was at it.

The PR could indeed have a more explicit title.
