### ISSUE TITLE
Remove SELinux

### ISSUE THREAD

**Issue by KellerFuchs** [hashbang/shell-etc#66]
Currently, SELinux is not doing anything:
```
% id
uid=3412(kellerfuchs) gid=3000 groups=3000 context=unconfined_u:unconfined_r:unconfined_t:SystemLow-SystemHigh

% sestatus -v
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             default
Current mode:                   permissive
Mode from config file:          permissive
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      29

Process contexts:
Current context:                unconfined_u:unconfined_r:unconfined_t:SystemLow-SystemHigh
Init context:                   unknown (No such file or directory)

File contexts:
Controlling terminal:           unconfined_u:object_r:user_devpts_t:SystemLow
/etc/passwd                     system_u:object_r:etc_t:SystemLow
/etc/shadow                     system_u:object_r:shadow_t:SystemLow
/bin/bash                       system_u:object_r:shell_exec_t:SystemLow
/bin/login                      system_u:object_r:login_exec_t:SystemLow
/bin/sh                         system_u:object_r:bin_t:SystemLow -> system_u:object_r:shell_exec_t:SystemLow
/sbin/agetty                    system_u:object_r:getty_exec_t:SystemLow
/sbin/init                      system_u:object_r:bin_t:SystemLow -> system_u:object_r:init_exec_t:SystemLow
/usr/sbin/sshd                  system_u:object_r:sshd_exec_t:SystemLow
```

Moreover, `etckeeper`'s history says that the configuration has never been modified: the only non-apt commits are `selinux/default/modules/active/commit_num` changes...

Given that the current state is basically `apt install selinux` and that noone is trying to do anything with it, I suggest we remove it outright and open a new issue for a useful MAC system:
- this removes useless complexity in the currently-running boxes;
- this let us to consider alternatives to SELinux if appropriate;
- this creates a vacuum in which a contributor can step up.

**Comment by KellerFuchs** [comment]
@hashbang/administrators Thoughts?

**Comment by daurnimator** [comment]
I thought we had an selinux setup. Need @deleriux2 or @lrvick to jump in here.

**Comment by gmcclins** [comment]
> Currently, SELinux is not doing anything:

I'm pretty sure its stopping systemd user services from starting

`Can't send to audit system: USER_AVC Unknown permission reload for class system exe="/lib/systemd/systemd" sauid=0 hostname=? `addr=?`

**Comment by KellerFuchs** [comment]
@gmcclins That's not SELinux.

**Comment by KellerFuchs** [comment]
@deleriux2 @lrvick Ping?

**Comment by ChickenNuggers** [comment]
@KellerFuchs Can we replicate a server, remove SELinux, reboot, and see what catches on fire?

**Comment by KellerFuchs** [comment]
@ChickenNuggers That's possible.  It is highly unlikely anything would, though, given that we do not run SELinux in enforce mode anyway.
I will try in a VM in the near future.

@deleriux2 @lrvick Re-ping.

**Comment by AlissaSquared** [comment]
We have the Atlantic.net password in the database; I believe we are allowed
another server for testing.

On Mon, Mar 7, 2016 at 11:50 AM The Fox in the Shell <
notifications@github.com> wrote:

> @ChickenNuggers <https://github.com/ChickenNuggers> That's possible. It
> is highly unlikely anything would, though, given that we do not run SELinux
> in enforce mode anyway.
> I will try in a VM in the near future.
>
> @deleriux2 <https://github.com/deleriux2> @lrvick
> <https://github.com/lrvick> Re-ping.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hashbang/shell-etc/issues/66#issuecomment-193367659>.
>
-- 

Ryan Rion <ryan@hashbang.sh>
Programmer :: Scripter :: Designer :: Administrator
https://github.com/ChickenNuggers

**Comment by KellerFuchs** [comment]
@ChickenNuggers Why on an Atlantic server when I can run the deploy scripts in a test VM, though?

**Comment by ChickenNuggers** [comment]
Whatever suits you.

**Comment by KellerFuchs** [comment]
@hashbang/administrators This was done on 2016-03-18.
Unfortunately, it seems that fully disabling SELinux requires a reboot.
This was done on `to1` right now, piggy-backing on the reboot for the kernel upgrade.  Other servers to be rebooted at 23:00 UTC.
