### ISSUE TITLE
User journals

### ISSUE THREAD

**Issue by daurnimator** [hashbang/shell-etc#68]
At the moment users do not have journals.
This means logs from their systemd units disappear into the aether.

**Comment by daurnimator** [comment]
This option seems relebant: https://www.freedesktop.org/software/systemd/man/journald.conf.html#SplitMode=

**Comment by daurnimator** [comment]
Looks like we don't have persistant logs.
Need to run:
```
mkdir -p /var/log/journal
systemd-tmpfiles --create --prefix /var/log/journal
journalctl --flush
```
as part of server initialisation. (`journal --flush` however doesn't exist in our old version of systemd, so we have to make do with `pkill -USR1 systemd-journal`)

**Comment by daurnimator** [comment]
> Need to run:
> ```
> mkdir -p /var/log/journal
> systemd-tmpfiles --create --prefix /var/log/journal
> journalctl --flush
> ```

I ran this manually on ny1 and now user journals work

**Comment by daurnimator** [comment]
Have manually run on all servers.

**Comment by KellerFuchs** [comment]
I guess we can close this.
