### ISSUE TITLE
Install guile-2.0-dev package

### ISSUE THREAD

**Issue by nckx** [hashbang/shell-etc#70]
*[Someone on IRC — I have a horrible memory and regret not remembering who — suggested I open an issue instead of a PR, so here it is. Apologies if this is in the wrong place.]*

Would it be possible to install the `guile-2.0-dev` package by default?

I'd be ever so chuffed.

**Comment by nckx** [comment]
(If `qemu` were available to users I'd be *more* than chuffed, but I suspect that might pushing it.)

**Comment by daurnimator** [comment]
Done. (both guide and qemu are now installed).

**Comment by nckx** [comment]
@daurnimator: oh wow. Thanks!
