### ISSUE TITLE
Inconsistent permissions between setup.sh and actual servers

### ISSUE THREAD

**Issue by KellerFuchs** [hashbang/shell-etc#84]
The permissions on `/var/run/utmp`, `/var/log/wtmp` and `/home` differ between what is actually present on the servers and what `setup.sh` does.

What is the right solution: keeping `/var/run/utmp`, `/var/log/wtmp` and `/home` world-readable or not?

**Comment by KellerFuchs** [comment]
PS: The discussion started in #83, but @daurnimator and I agreed to move it to a separate issue.

**Comment by daurnimator** [comment]
yeah something is undoing the permissions changes setup.sh does.
We sort of knew about this, but never managed to track it down.

**Comment by KellerFuchs** [comment]
@daurnimator Ok, so the permissions shoud be as follows?
```
/var/run/utmp      660
/var/log/wtmp      660
/var/log/lastlog   660
/home              711
```

Can we have a rationale for that?
Especially having `/home` non-readable feels dodgy, and people can query the list of users from LDAP or from nsswitch anyhow.

**Comment by KellerFuchs** [comment]
@daurnimator Ping?

**Comment by ChickenNuggers** [comment]
Is there a reason that we block `/home`? Also, `660/660/660` seems fine for the other three files IMO; I don't think anything breaks without the readability of those files. If something does, we can document it in this issue and in the commit history of `setup.sh`.

**Comment by KellerFuchs** [comment]
Not breaking anything is not a rationale, though, and we still don't know why `/home` should be `chmod 0000`.

**Comment by daurnimator** [comment]
> Can we have a rationale for that?
> Especially having /home non-readable feels dodgy, and people can query the list of users from LDAP or from nsswitch anyhow.

I don't think we *should* allow public listing from ldap.

Otherwise we want to prevent users knowing other user's usage patterns: whether they're logged on, what programs they're running, etc.

**Comment by KellerFuchs** [comment]
@daurnimator I agree we should, within reasonable bounds, not leak information about users.
The thing is that it feels you want to put weird permissions on `/home` to prevent listing users, and that's where it gets a bit silly: POSIX litteraly mandates that users can be looked up; see `getpwent(3)`.

For the other ones, I can agree to `chmod 0660`.

**Comment by daurnimator** [comment]
btw, not sure if this fixes the inconsistency.
Previously the servers kept changing the permissions back: we need to figure out when+what is doing it.

**Comment by KellerFuchs** [comment]
@daurminator Sure, but we cannot test & solve that without more details, which we cannot get without being able to reproduce.
FWIW, I checked that those files are not owned by any Debian package, otherwise `dpkg-statoverride(1)` would have been the way to go.
