### ISSUE TITLE
"You have new mail." on login -- no, I don't!

### ISSUE THREAD

**Issue by quite** [hashbang/shell-etc#90]
Upon login, the message "You have new mail." is displayed as part of the login messages (motd, pam, etc?). But, my ~/Mail Maildir does not have any new mail. This is probably governed by pam_mail module in `/etc/pam.d/login`, which I must say looks OK (though I'm no authority on PAM).

**Comment by ChickenNuggers** [comment]
/me glares at /var/spool/mail

I don't actually know what causes that message; I don't ever see it.

**Comment by KellerFuchs** [comment]
That's *weird*.

@ChickenNuggers I'm not even sure `/var/spool/mail` should be involved at all

**Comment by ChickenNuggers** [comment]
It might not but I'm guessing that's where it checks.

**Comment by gmcclins** [comment]
For local logins, this is /etc/pam.d/login. For ssh, it is /etc/pam.d/sshd. Looking at sshd it shows

`session    optional     pam_mail.so dir=~/Mail standard noenv # [1]`

Just a stab in the dark here, but maybe it needs to be ~/Mail/new

**Comment by daurnimator** [comment]
> Just a stab in the dark here, but maybe it needs to be ~/Mail/new

Nope. the way pam_mail.so works is that checks if the `new` dir contains any files.
https://git.fedorahosted.org/cgit/linux-pam.git/tree/modules/pam_mail/pam_mail.c#n216

Looking at my own Mail/new directory, it contains `.gitkeep`!

```
$ ls -lA Mail/new/
total 0
-rw-r--r-- 1 daurnimator daurnimator 0 May 11  2015 .gitkeep
```

**Comment by daurnimator** [comment]
> Deleting the .gitkeep should make the new mail message work as intended.

i.e. reverting https://github.com/hashbang/dotfiles/commit/6eaf4ef71baf77eed7bc6b8b5cac1df58b07d16b should fix things.
@lrvick its all your fault ;)
