### ISSUE TITLE
please install Tor and Torsocks/Torify

### ISSUE THREAD

**Issue by jericho320** [hashbang/shell-etc#94]
Please install Tor (default node/proxy setup) and Torify packages so our user can use tor proxy for outgoing connections)

**Comment by KellerFuchs** [comment]
@hashbang/administrators Any objections?

FYI, I would like us to set `IsolatePID 1` in `/etc/tor/torsocks.conf`: it makes connections done by different processes use different Tor circuits, thus guaranteeing that connections done by different users cannot be linked together.

**Comment by lrvick** [comment]
+1

**Comment by KellerFuchs** [comment]
@lrvick OK, doing that
