### ISSUE TITLE
Make our Tor instances be relays

### ISSUE THREAD

**Issue by KellerFuchs** [hashbang/shell-etc#95]
This is a follow-up on #94 

Currently, we have on-server Tor instances that only act as proxies (for those of our users who use them explicitely).  We can easily set them to accept to carry Tor traffic.

To be very clear, I am **not** suggesting we let them be exit nodes: traffic won't exit the Tor network through our servers, Atlantic.net won't receive Tor-related `abuse@` complains, etc...

Pro:
- more effective at anonymizing our Tor-using users, against a network-level adversary;
- warm, fuzzy feeling because we help people around the world.

Con:
- increased bandwidth use, up to the bandwidth cap we set.

**Comment by lrvick** [comment]
Atlantic.net is donating bandwidth/data specifically for #! shell related traffic/activities with the agreement everyone using our resources sees the "sponsored by atlantic.net" ad. They trade us bandwidth for us giving them a little exposure to a community of engineers. Opening TOR  public traffic means random people using the donated bandwidth without ever seeing the ad which kind of goes outside of our handshake agreement.

**Comment by KellerFuchs** [comment]
@lrvick That's fair enough.
